apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ptinbd
  namespace: prod
spec:
  instances: 3
  storage:
    size: "10Gi"
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  bootstrap:
    initdb:
      database: prod
      owner: ptincatering
      secret:
        name: postgresql-secret

  monitoring:
    enablePodMonitor: true


  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
