namespace:
  name: testing
  env: dev
  team: ptincatering

db:
  clusterName: ptinbd-test
  instances: 2
  storageSize: "5Gi"
  databaseName: test
  resources:
    requests:
      memory: "300Mi" 
      cpu: "200m"
    limits:
      memory: "500Mi"
      cpu: "400m"
  externalAccess:
    enabled: true
    rwPort: 30432
    roPort: 30433

back:
  replicas: 1
  canary:
    setWeight:
      Weight1: 20
      Weight2: 50
    pause:
      duration1: 1m
      duration2: 1m
  image:
    repository: ptincatering/catering-back-test
    tag: v2.6
  resources:
    requests:
      memory: "300Mi"
      cpu: "250m"
    limits:
      memory: "600Mi"
      cpu: "500m"
  nodePort:
    enabled: true
    manualPort: 30080
  volumes:
    pvc:
      name: pvc-testing

front:
  replicas: 1
  canary:
    setWeight:
      Weight1: 20
      Weight2: 50
    pause:
      duration1: 1m
      duration2: 1m
  image:
    repository: ptincatering/catering-frontend-dev
    tag: v4.21
  url:
    external: "http://ptincatering-me"
    internal: "http://ptin-back-stable:8080"
  resources:
    requests:
      memory: "250Mi"
      cpu: "250m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  nodePort:
    enabled: true
    manualPort: 30081

ingress:
  host: ptincatering-test.me

rbac:
  rules:
    - apiGroups: ["argoproj.io"]
      resources: ["rollouts"]
      verbs: ["get", "list", "watch", "create", "update"]

    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list", "watch", "create", "update"]

    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["*"]

    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]

    - apiGroups: [""]
      resources: ["secrets", "serviceaccounts"]
      verbs: ["*"]

    - apiGroups: ["rbac.authorization.k8s.io"]
      resources: ["roles", "rolebindings"]
      verbs: ["*"]

    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["*"]

    - apiGroups: ["postgresql.cnpg.io"]
      resources: ["clusters"]
      verbs: ["*"]
