namespace:
  name: prod
  env: prod
  team: ptincatering

db:
  clusterName: ptinbd
  instances: 3
  storageSize: "10Gi"
  databaseName: prod
  resources:
    requests:
      memory: "256Mi" 
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

back:
  canary:
    setWeight:
      Weight1: 20
      Weight2: 50
    pause:
      duration1: 5m
      duration2: 2m
  image:
    repository: ptincatering/catering-back
    tag: v2.11
  resources:
    requests:
      memory: "600Mi"
      cpu: "400m"
    limits:
      memory: "1Gi"
      cpu: "700m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    cpuTarget: 50
    memoryTarget: 500Mi
  volumes:
    pvc:
      name: pvc-production
front:
  canary:
    setWeight:
      Weight1: 20
      Weight2: 50
    pause:
      duration1: 5m
      duration2: 2m
  image:
    repository: ptincatering/catering-frontend
    tag: v4.1
  url:
    external: "https://ptincatering.me"
    internal: "http://ptin-back-stable:8080"
  resources:
    requests:
      memory: "500Mi"
      cpu: "400m"
    limits:
      memory: "1Gi"
      cpu: "700m"
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    cpuTarget: 50
    memoryTarget: 500Mi

ingress:
  host: ptincatering.me

rbac:
  rules:
    - apiGroups: ["argoproj.io"]
      resources: ["rollouts"]
      verbs: ["*"]

    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list", "watch", "create", "update"]

    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["*"]

    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]

    - apiGroups: [""]
      resources: ["secrets", "serviceaccounts"]
      verbs: ["*"]

    - apiGroups: ["rbac.authorization.k8s.io"]
      resources: ["roles", "rolebindings"]
      verbs: ["*"]

    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["*"]

    - apiGroups: ["postgresql.cnpg.io"]
      resources: ["clusters"]
      verbs: ["*"]
