db:
  secretName: postgresql-secret
  username: ptincatering
  password: ptincatering
  maxConnections: 200
  user: ptincatering
  monitoring:
    enabled: true
  externalAccess:
    enabled: false

back:
  name: ptin-back
  hpa:
    enabled: false
  nodePort:
    enabled: false

front:
  name: ptin-front
  hpa:
    enabled: false

ingress:
  name: app-ingress

