apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-production
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-production
  resources:
    requests:
      storage: 20Gi
