apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.back.name }}-stable
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.back.name }}-app
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.back.name }}-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
