apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.front.name }}-config
  namespace: {{ .Values.namespace.name }}
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      "API_URL_EXTERNAL": "{{ .Values.front.url.external }}",
      "API_URL_INTERNAL": "{{ .Values.front.url.internal }}",
      "OTEL_URL": "/api/otlp",
      "ENVIRONMENT": "{{ .Values.namespace.name }}"
    }

  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
             root /usr/share/nginx/html;
             index index.html;
             try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass {{ .Values.front.url.internal }};
            proxy_set_header Host $host;
            proxy_set_header X-REAL-IP $remote_addr;
        }

        location /api/otlp/ {
            proxy_pass http://my-otel-collector-opentelemetry-collector.default.svc.cluster.local:4318/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-REAL-IP $remote_addr;
        }

        location /api/images {
            alias /mnt/storage/imagenes/;
        }
    }
