apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.front.name }}-app
  ports:
    - port: 80
      targetPort: 80
