{{- if .Values.back.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.back.name }}-hpa
  namespace: {{ .Values.namespace.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.back.name }}
  minReplicas: {{ .Values.back.hpa.minReplicas }}
  maxReplicas: {{ .Values.back.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.back.hpa.cpuTarget }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.back.hpa.memoryTarget }}
{{- end }}
