apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    nginx.ingress.kubernetes.io/affinity: {{ .Values.ingress.nginx.affinity | quote }}
    nginx.ingress.kubernetes.io/session-cookie-name: {{ .Values.ingress.nginx.session_cookie_name | quote }}
    nginx.ingress.kubernetes.io/session-cookie-expires: {{ .Values.ingress.nginx.session_cookie_expires | quote }}
    nginx.ingress.kubernetes.io/session-cookie-max-age: {{ .Values.ingress.nginx.session_cookie_max_age | quote }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.front.name }}-stable
            port:
              number: 80
