apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ptinbd-test    # <--- IMPORTANTE: Este nombre debe coincidir con el selector de abajo
  namespace: testing
spec:
  instances: 3         # Para pruebas con 1 es suficiente, puedes poner 3 si quieres alta disponibilidad
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: test
      owner: ptincatering
      secret:
        name: postgresql-secret
