apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  namespace: monitoring
  labels:
    release: monitor
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  - port: prometheus-app
    interval: 10s
    path: /metrics
