name: CI y CD (Testing)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar código
        run: mvn clean compile -DskipTests

      - name: Análisis de Formato y Linting
        run: mvn checkstyle:check -Dcheckstyle.failOnViolation=false

  build-and-push:
    needs: [ci]
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.TAG }}
      DIGEST: ${{ steps.build.outputs.digest }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Infraestructura
        uses: actions/checkout@v4
        with:
          repository: 'PTIN-projecte/infrastructure-devops'
          path: infra
          token: ${{ secrets.INFRA_TOKEN }}

      - name: Generar tag
        id: tag
        run: echo "TAG=v${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push imagen
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/BackDockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catering-back-test:${{ steps.tag.outputs.TAG }}

      - name: Guardar metadata como artifact
        run: |
          echo "${{ steps.build.outputs.digest }}" > digest-back.txt
          echo "${{ steps.tag.outputs.TAG }}" > tag-back.txt
          echo "${{ github.sha }}" > commit-sha.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: digest-back-${{ github.sha }}
          path: |
            digest-back.txt
            tag-back.txt
            commit-sha.txt
          retention-days: 30

  deploy-testing:
    needs: [build-and-push]
    runs-on: self-hosted
    environment: testing
    steps:
      - name: Checkout Infraestructura
        uses: actions/checkout@v4
        with:
          repository: 'PTIN-projecte/infrastructure-devops'
          path: infra
          token: ${{ secrets.INFRA_TOKEN }}
          persist-credentials: false

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.14.0'

      - name: Helm deploy testing
        run: |
          export KUBECONFIG=/home/github-runner/actions-runner/.kube/config-testing
          cd infra/Kubernetes/ptincatering
          helm upgrade --install ptin-test . \
            --reuse-values \
            --namespace testing \
            --set back.image.tag=${{ needs.build-and-push.outputs.TAG }}